package com.coderstudio.tomliang.minishcap.dao;

import com.coderstudio.tomliang.minishcap.bean.Favorites;
import com.coderstudio.tomliang.minishcap.bean.History;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoritesDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final FavoritesDao favoritesDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoritesDaoConfig = daoConfigMap.get(FavoritesDao.class).clone();
        favoritesDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        favoritesDao = new FavoritesDao(favoritesDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Favorites.class, favoritesDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        favoritesDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
    }

    public FavoritesDao getFavoritesDao() {
        return favoritesDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
