package com.coderstudio.tomliang.fe_webviewtool.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY".
 */
@Entity
public class History {

    @Id
    @NotNull
    @Unique
    private String url;
    private Integer count;

    @Generated(hash = 869423138)
    public History() {
    }

    public History(String url) {
        this.url = url;
    }

    @Generated(hash = 698247613)
    public History(@NotNull String url, Integer count) {
        this.url = url;
        this.count = count;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
